name: loren alonzo
favicon: null
layout_spectrum: 0.9956
typography_spectrum: 0.49622
title: "A bikini competitor's fitness journey..."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#ffffff'
    - '#a1c6d9'
    - '#68899a'
    - '#c56c4c'
  brandStrength: 1
  lightness: 0.619595160940662
  saturation: 0.27924211136996746
  rhythmicContrast: 0.5
purpose: []
