name: lorenalonzo
favicon: null
layout_spectrum: 0.7346528631169349
typography_spectrum: 0.8958273748867214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7102965046651661
  lightness: 0.619595160940662
  saturation: 0.27924211136996746
  rhythmicContrast: 0.792649855138734
purpose: []
