name: lorenalonzo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8958273748867214
title: Hello World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#ffffff'
    - '#a1c6d9'
    - '#68899a'
    - '#c56c4c'
  brandStrength: 0.7102965046651661
  lightness: 0.619595160940662
  saturation: 0.27924211136996746
  rhythmicContrast: 0.792649855138734
purpose: []
